-- 1. Add Ticket Column (Safe if exists)
ALTER TABLE public.permohonan_data
ADD COLUMN IF NOT EXISTS no_tiket TEXT;

-- 2. Add Unique Constraint to Ticket Number
-- We use a unique index which is cleaner for text columns
CREATE UNIQUE INDEX IF NOT EXISTS idx_permohonan_no_tiket_unique ON public.permohonan_data (no_tiket);

-- 3. Add Check Constraint for Status (Enhancing existing status column)
-- This ensures only valid statuses are entered
ALTER TABLE public.permohonan_data 
DROP CONSTRAINT IF EXISTS permohonan_status_check;

ALTER TABLE public.permohonan_data
ADD CONSTRAINT permohonan_status_check 
CHECK (status IN ('pending', 'approved', 'rejected', 'completed'));

-- 4. Function: Generate Ticket Number
-- Logic: Prefix + First 8 chars of UUID
CREATE OR REPLACE FUNCTION public.handle_new_permohonan_ticket()
RETURNS TRIGGER AS $$
DECLARE
    prefix text;
    id_part text;
BEGIN
    -- Determine Prefix based on 'keperluan' (Service Type)
    -- Adjust these string matches if your frontend values change!
    IF NEW.keperluan ILIKE '%Banjir%' THEN
        prefix := 'B';
    ELSIF NEW.keperluan ILIKE '%Petir%' THEN
        prefix := 'P';
    ELSIF NEW.keperluan ILIKE '%Konsultasi%' THEN
        prefix := 'K';
    ELSIF NEW.keperluan ILIKE '%Nol Rupiah%' THEN
        prefix := '0';
    ELSE
        prefix := 'U'; -- U for Undefined/General
    END IF;

    -- Extract first 8 chars of the UUID (The ID is already generated by DEFAULT gen_random_uuid())
    -- NEW.id might be null in BEFORE trigger if it's auto-generated by the table default? 
    -- Actually, for gen_random_uuid() default, we might need to fetch it or let Postgres handle it.
    -- However, in BEFORE INSERT, NEW.id is usually available if provided, or we can force it if null.
    
    IF NEW.id IS NULL THEN
       NEW.id := gen_random_uuid();
    END IF;

    id_part := upper(substring(NEW.id::text from 1 for 8));

    -- Set the ticket number
    NEW.no_tiket := prefix || '-' || id_part;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Trigger: Auto-generate on Insert
DROP TRIGGER IF EXISTS trigger_generate_ticket ON public.permohonan_data;

CREATE TRIGGER trigger_generate_ticket
BEFORE INSERT ON public.permohonan_data
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_permohonan_ticket();

-- 6. Function: Prevent Ticket Updates
CREATE OR REPLACE FUNCTION public.prevent_ticket_update()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.no_tiket IS DISTINCT FROM NEW.no_tiket THEN
        RAISE EXCEPTION 'Ticket number (no_tiket) cannot be modified once generated.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 7. Trigger: Protect Ticket on Update
DROP TRIGGER IF EXISTS trigger_protect_ticket ON public.permohonan_data;

CREATE TRIGGER trigger_protect_ticket
BEFORE UPDATE ON public.permohonan_data
FOR EACH ROW
EXECUTE FUNCTION public.prevent_ticket_update();
